WebRazorPagesGlobalization/Models/IServiceLocalizer.cs
using Microsoft.AspNetCore.Mvc.Localization;
using Microsoft.Extensions.Localization;
namespace WebRazorPagesGlobalization.Models
{
    public interface IServiceLocalizer<T>
    {
        IStringLocalizer<T> StringLocalizer { get; }
        IHtmlLocalizer<T> HtmlLocalizer { get; }
        LocalizedString GetString(string name);
        LocalizedString GetHtmlString(string name);
    }
}

WebRazorPagesGlobalization/Models/ServiceLocalizer.cs
using Microsoft.AspNetCore.Mvc.Localization;
using Microsoft.Extensions.Localization;
using WebRazorPagesGlobalization.Pages;

namespace WebRazorPagesGlobalization.Models
{
    public abstract class ServiceLocalizer<T>: IServiceLocalizer<T>
    {
        public IStringLocalizer<T> StringLocalizer { get; }
        public IHtmlLocalizer<T> HtmlLocalizer { get; }

        public ServiceLocalizer(IStringLocalizer<T> stringLocalizer, IHtmlLocalizer<T> htmlLocalizer)
        {
            StringLocalizer = stringLocalizer;
            HtmlLocalizer = htmlLocalizer;
        }

        public LocalizedString GetString(string name)
        {
            return StringLocalizer.GetString(name);
        }

        public LocalizedString GetHtmlString(string name)
        {
            return HtmlLocalizer.GetString(name);
        }
    }

    public interface IServiceLocalizerIndexModel: IServiceLocalizer<IndexModel> { }

    public class ServiceLocalizerIndexModel : ServiceLocalizer<IndexModel>, IServiceLocalizerIndexModel
    {
        public ServiceLocalizerIndexModel(
            IStringLocalizer<IndexModel> stringLocalizer, 
            IHtmlLocalizer<IndexModel> htmlLocalizer) 
            : base(stringLocalizer, htmlLocalizer)
        {
        }
    }
}

WebRazorPagesGlobalization/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Localization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Localization;

namespace WebRazorPagesGlobalization.Pages
{
    public class AboutModel : PageModel
    {
        public IStringLocalizer StringLocalizer { get; }
        public IHtmlLocalizer HtmlLocalizer { get; }

        public AboutModel(IHtmlLocalizer<AboutModel> htmlLocalizer, IStringLocalizer<AboutModel> stringLocalizer)
        {
            HtmlLocalizer = htmlLocalizer;
            StringLocalizer = stringLocalizer;

        }
        public void OnGet()
        {
            ViewData["Title"] = StringLocalizer.GetString("Title");
        }
    }
}

WebRazorPagesGlobalization/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Localization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Localization;
using WebRazorPagesGlobalization.Models;

namespace WebRazorPagesGlobalization.Pages
{
    public class IndexModel : PageModel
    {
        public IServiceLocalizerIndexModel Localizer { get; }
        public IndexModel(IServiceLocalizerIndexModel localizer)
        {            
            Localizer = localizer;
        }       

        public void OnGet()
        {
            ViewData["Title"] = Localizer.GetString("Title");
        }

        [HttpPost]
        public IActionResult OnPostLanguage(string culture, string returnUrl = "/Index")
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return LocalRedirect(returnUrl);
        }
    }
}

//WebRazorPagesGlobalization.Resources.Pages.IndexModel

WebRazorPagesGlobalization/Pages/About.cshtml
@page
@using Microsoft.AspNetCore.Mvc.Localization
@model WebRazorPagesGlobalization.Pages.AboutModel
@inject IHtmlLocalizer<AboutModel> HtmlLocalizer


<h2>@ViewData["Title"]</h2>

<h3>@HtmlLocalizer.GetString("Title")</h3>
<h3>@HtmlLocalizer.GetString("Status")</h3>

<p>
    @System.Globalization.CultureInfo.CurrentCulture.Name
</p>
<p>
    @DateTime.Now.ToLongDateString()
</p>

WebRazorPagesGlobalization/Pages/Index.cshtml
@page
@model IndexModel
@using Microsoft.AspNetCore.Mvc.Localization
@inject IHtmlLocalizer<IndexModel> HtmlLocalizer
<br />
<p>
    @ViewData["Title"]
</p>

<p> @DateTime.Now </p>

<div class="row">
    <div class="col-lg-4">
        <form asp-page="Index" asp-page-handler="Language" method="post">
            <input type="hidden" name="culture" id="culture" value="en-US" />
            <button>Idioma Americano</button>
        </form>
    </div>
    <div class="col-lg-4">
        <form asp-page="Index" asp-page-handler="Language" method="post">
            <input type="hidden" name="culture" id="culture" value="pt-BR" />
            <button>Idioma Brasil</button>
        </form>
    </div>
</div>

<h3>@HtmlLocalizer.GetString("Frase")</h3>


@System.Globalization.CultureInfo.CurrentCulture.DisplayName

WebRazorPagesGlobalization/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebRazorPagesGlobalization</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-page="/Index" class="navbar-brand">WebRazorPagesGlobalization</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-page="/Index">Home</a></li>
                    <li><a asp-page="/About">About</a></li>
                    <li><a asp-page="/Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    @*<partial name="_CookieConsentPartial" />*@

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - WebRazorPagesGlobalization</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>